<img src="./img/p1/portada.png" />

###  Pregunta [1]: Implemente mediante un programa Python la asignación del reparto de escaños de una circunscripción electoral usando la Ley D’Hondt. Los datos se pueden introducir por teclado o leerse desde un fichero.

In [2]:
import numpy as np
import sys

L_Partidos = []
escano = int(input("¿Escaños?: "))
partidos = int(input("¿Partidos?: "))

for x in range(0, partidos):
    P = dict()
    print("\nDatos del partido: ")
    P["name"] = input("Nombre Partido: ")
    P["votes"] = int(input("Votos: "))
    P["escano"] = 0
    L_Partidos.append(P)

print(L_Partidos)
M = np.zeros(shape=(partidos, escano))

for i in range(0, partidos):
    for j in range(0, escano):
        M[i][j] = L_Partidos[i]["votes"] / (j + 1)

aux = 0
while aux < escano:
    where = np.where(M == np.max(M))
    M[where[0][0]][where[1][0]] = -1
    L_Partidos[where[0][0]]["escano"] += 1
    aux += 1

for i in range(0, partidos):
    print(L_Partidos[i]["name"], " tiene ", L_Partidos[i]["votes"], "votos , tiene", L_Partidos[i]["escano"],
          " escaños.")

¿Escaños?: 14
¿Partidos?: 3

Datos del partido: 
Nombre Partido: PSOE
Votos: 122

Datos del partido: 
Nombre Partido: PP
Votos: 87

Datos del partido: 
Nombre Partido: VOX
Votos: 50
[{'name': 'PSOE', 'votes': 122, 'escano': 0}, {'name': 'PP', 'votes': 87, 'escano': 0}, {'name': 'VOX', 'votes': 50, 'escano': 0}]
PSOE  tiene  122 votos , tiene 7  escaños.
PP  tiene  87 votos , tiene 5  escaños.
VOX  tiene  50 votos , tiene 2  escaños.


###  Pregunta [2]:Implemente un programa Python que genere aleatoriamente una matriz de valores reales de un tamaño indicadopor teclado. Sobre la matriz generada realice las siguientes operaciones:

    2.1. Obtenga los valores máximos y mínimos de la matriz.
    2.2. Use el producto escalar para obtener el ángulo formado por dos
         vectores fila o columna solicitados porteclado.

In [2]:
import numpy as NP
import math
def createMatrixByKeyboard():
    filas = int(input("\nFilas: "))
    columnas = int(input("\nColumnas: "))
    m = NP.zeros((filas, columnas))
    for i in range(filas):
        for j in range(columnas):
            dat = int(input("\nDato en ["+str(i)+"]["+str(j)+"]:"))
            m[i][j]=dat
    return m
m = createMatrixByKeyboard()
print("\n --------RESULTADOS--------")
print("\n   Apartado 2.1")
print("\n   ---> Valor maximo: "+str(m.max()))
print("\n   ---> Valor minimo: "+str(m.min()))
print("\n   Apartado 2.2")
print(m)
flag = 0
aux=[]
while flag!=2:
    
    opt = int(input("\n (1) Para selecionar una fila, (2) Para seleccionar una columna: "))

    if opt == 1:
        value = int(input("\n Introduce la fila a calcular: "))
        aux.append(m[value,:])
        flag=flag+1    
    elif opt ==2:
        value = int(input("\n Introduce la columna a calcular: "))
        aux.append(m[:,value])
        flag=flag+1
    else:
        print("\nValor incorrecto")

numerador = NP.dot(aux[0], aux[1])
denominador = (NP.linalg.norm(aux[0])*NP.linalg.norm(aux[1]))
print("El angulo en radianes es: "+str(numerador/denominador)+"")
print("El angulo en grados es: "+str((NP.arccos(numerador/denominador) * 180 / math.pi))+"")


Filas: 3

Columnas: 3

Dato en [0][0]:1

Dato en [0][1]:2

Dato en [0][2]:3

Dato en [1][0]:4

Dato en [1][1]:5

Dato en [1][2]:6

Dato en [2][0]:7

Dato en [2][1]:8

Dato en [2][2]:9

 --------RESULTADOS--------

   Apartado 2.1

   ---> Valor maximo: 9.0

   ---> Valor minimo: 1.0

   Apartado 2.2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

 (1) Para selecionar una fila, (2) Para seleccionar una columna: 1

 Introduce la fila a calcular: 1

 (1) Para selecionar una fila, (2) Para seleccionar una columna: 1

 Introduce la fila a calcular: 0
El angulo en radianes es: 0.9746318461970762
El angulo en grados es: 12.933154491899135


###  Pregunta [3]:Implemente un programa Python que lea una matriz de número reales desde teclado de una dimensión dada. A partir de la matriz leída debe calcular la siguiente información:
    3.1. Máximo por filas y por columnas
    3.2. Determinante de la matriz.

In [8]:
import numpy as NP
import math
def createMatrixByKeyboard():
    filas = int(input("\nFilas: "))
    columnas = int(input("\nColumnas: "))
    m = NP.zeros((filas, columnas))
    for i in range(filas):
        for j in range(columnas):
            dat = int(input("\nDato en ["+str(i)+"]["+str(j)+"]:"))
            m[i][j]=dat
    return m
m = createMatrixByKeyboard()
print("\n --------RESULTADOS--------")
print("\n   Apartado 3.1")
print(m)
for i in range(NP.size(m,1)):
    print("Valor maximo de la fila "+str(i)+": "+str(NP.max(m[i,:])))
    print("Valor minimo de la fila "+str(i)+": "+str(NP.min(m[i,:])))

for i in range(NP.size(m,0)):
    print("Valor maximo de la columna "+str(i)+": "+str(NP.max(m[:,i])))
    print("Valor minimo de la columna "+str(i)+": "+str(NP.min(m[:,i])))
print("\n   Apartado 3.2")

print("Determinante de la matriz: "+str(round(NP.linalg.det(m))))

print("\n   Apartado 3.3")

print("Rango de la matriz: "+str(NP.linalg.matrix_rank(m)))


Filas: 3

Columnas: 3

Dato en [0][0]:1

Dato en [0][1]:2

Dato en [0][2]:3

Dato en [1][0]:4

Dato en [1][1]:5

Dato en [1][2]:6

Dato en [2][0]:7

Dato en [2][1]:8

Dato en [2][2]:9

 --------RESULTADOS--------

   Apartado 3.1
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Valor maximo de la fila 0: 3.0
Valor minimo de la fila 0: 1.0
Valor maximo de la fila 1: 6.0
Valor minimo de la fila 1: 4.0
Valor maximo de la fila 2: 9.0
Valor minimo de la fila 2: 7.0
Valor maximo de la columna 0: 7.0
Valor minimo de la columna 0: 1.0
Valor maximo de la columna 1: 8.0
Valor minimo de la columna 1: 2.0
Valor maximo de la columna 2: 9.0
Valor minimo de la columna 2: 3.0

   Apartado 3.2
Determinante de la matriz: 0.0

   Apartado 3.3
Rango de la matriz: 2


###  Pregunta [4]:Implemente un programa Python que lea una matriz de número enteros desde teclado de una dimensión dada. A partir de la matriz leída debe calcular la siguiente información:
    4.1. Moda de la matriz.
    4.2. Media de todos los elementos de la matriz.

In [13]:
import numpy as NP
import math
from scipy import stats as ST
def numpyCalMode(matrix):
    aux=[]
    for i in range(NP.size(matrix,1)):
        for j in range(NP.size(matrix,0)):
            aux.append(matrix[i][j])  
    return ST.mode(aux)[0][0]
def createMatrixByKeyboard():
    filas = int(input("\nFilas: "))
    columnas = int(input("\nColumnas: "))
    m = NP.zeros((filas, columnas))
    for i in range(filas):
        for j in range(columnas):
            dat = int(input("\nDato en ["+str(i)+"]["+str(j)+"]:"))
            m[i][j]=dat
    return m
m = createMatrixByKeyboard()
print(m)
print("\n --------RESULTADOS--------")
print("\n   Apartado 4.1")
print("\n   ---> La moda es: "+str(numpyCalMode(m)))
print("\n   Apartado 4.2")
print("\n   ---> La media es: "+str(NP.average(m)))


Filas: 3

Columnas: 3

Dato en [0][0]:1

Dato en [0][1]:2

Dato en [0][2]:3

Dato en [1][0]:4

Dato en [1][1]:5

Dato en [1][2]:5

Dato en [2][0]:6

Dato en [2][1]:7

Dato en [2][2]:8
[[1. 2. 3.]
 [4. 5. 5.]
 [6. 7. 8.]]

 --------RESULTADOS--------

   Apartado 4.1

   ---> La moda es: 5.0

   Apartado 4.2

   ---> La media es: 4.555555555555555


###  Pregunta [5]:Implemente un programa Python que lea una matriz de número reales desde un fichero texto con formato libre. Una vez leído el programa debe obtener la inversa de la matriz y realizar un producto matricial para comprobar que el cálculo de la inversa es correcto.

In [1]:
import numpy as NP
import math
def openMatrixFiledata(nameFile,deli):
    openFile = NP.loadtxt("./data/p1/"+nameFile, delimiter=deli)
    return openFile

file = input("\n Inserte el nombre del fichero: ")
delimiter = input("\n Inserte el delimitador del fichero: ")

m = openMatrixFiledata(file,delimiter)
print("\n --------Matrix Leida--------")
print(m)
print("\n --------RESULTADOS--------")
inversa = NP.linalg.inv(m)
print("\n   ---> Inversa: ")
print(inversa)
print("\n   ---> Producto m*m-1: ")
multi = NP.matmul(m,inversa)
print(multi)

indentidad = NP.identity(NP.size(m,1))
if NP.array_equal(indentidad,multi)==True:
    print("Es correcto\n")



 Inserte el nombre del fichero: datos1.txt

 Inserte el delimitador del fichero:  

 --------Matrix Leida--------
[[ 1. -1.  2.]
 [-2.  0.  4.]
 [ 0. -2.  7.]]

 --------RESULTADOS--------

   ---> Inversa: 
[[ 4.   1.5 -2. ]
 [ 7.   3.5 -4. ]
 [ 2.   1.  -1. ]]

   ---> Producto m*m-1: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Es correcto

